name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@master
    
    - name: Deploy to Netlify
      id: netlify
      uses: ivanjosipovic/actions/cli@dev2
      with:
        args: deploy1 --json -d .
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
    - name: Set Test Address
      run: |
        $url = $(ConvertFrom-Json '${{ steps.netlify.outputs.output }}').deploy_url;
        Write-Output $url;
      shell: pwsh
